In [75]:
%pip install pandas numpy plotly ipywidgets nbformat

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: numpy in /usr/local/python/3.12.1/lib/python3.12/site-packages (2.5.1)
Requirement already satisfied: plotly in /usr/local/python/3.12.1/lib/python3.12/site-packages (6.9.0)
Requirement already satisfied: ipywidgets in /usr/local/python/3.12.1/lib/python3.12/site-packages (8.1.8)
Requirement already satisfied: nbformat in /home/codespace/.local/lib/python3.12/site-packages (5.10.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: narwhals>=1.15.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from plotly) (2.24.0)
Requirement already satisfied: packaging in /home/codespace/.local/lib/python3.12/site-packages (from plotly) (26.0)
Requirement already satisfied: comm>=0.1.3 in /home/codespace/.local/lib/python3.12/site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /home/codespace/.local/lib/python3.12/site-packages (from ipywidgets) (9.11.0)
Requirement already satisfied: traitlets>=4.3.1 in /home/codespace/.local/lib/python3.12/site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: fastjsonschema>=2.15 in /home/codespace/.local/lib/python3.12/site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /home/codespace/.local/lib/python3.12/site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/codespace/.local/lib/python3.12/site-packages (from nbformat) (5.9.1)
Requirement already satisfied: decorator>=5.1.0 in /home/codespace/.local/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /home/codespace/.local/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /home/codespace/.local/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in /home/codespace/.local/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: pexpect>4.6 in /home/codespace/.local/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/codespace/.local/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in /home/codespace/.local/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in /home/codespace/.local/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in /home/codespace/.local/lib/python3.12/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /home/codespace/.local/lib/python3.12/site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.6)
Requirement already satisfied: attrs>=22.2.0 in /home/codespace/.local/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/codespace/.local/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /home/codespace/.local/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /home/codespace/.local/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /home/codespace/.local/lib/python3.12/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.4)
Requirement already satisfied: ptyprocess>=0.5 in /home/codespace/.local/lib/python3.12/site-packages (from pexpect>4.6->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /home/codespace/.local/lib/python3.12/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)
Requirement already satisfied: executing>=1.2.0 in /home/codespace/.local/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/codespace/.local/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in /home/codespace/.local/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [76]:
import pandas as pd
import plotly.express as px
import numpy as np 
import unicodedata
from ipywidgets import interact, interactive, Dropdown, IntRangeSlider
from IPython.display import display, clear_output

#df = pd.read_csv('spotify-2023.csv', encoding='utf-8') #cannot read the whole file once bumping into errors
with open('spotify-2023.csv', mode='r', encoding='utf-8', errors='replace') as f:
    df = pd.read_csv(f)
df.head()

In [77]:
df = pd.read_csv('spotify-2023.csv', encoding='cp1252')
df.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6

In [78]:
df.describe()

,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,in_apple_playlists,in_apple_charts,in_deezer_charts,bpm,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
count,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,953.00000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000
mean,1.556139,2018.238195,6.033578,13.930745,5200.124869,12.009444,67.812172,51.908709,2.666317,122.540399,66.96957,51.431270,64.279119,27.057712,1.581322,18.213012,10.131165
std,0.893044,11.116218,3.566435,9.201949,7897.608990,19.575992,86.441493,50.630241,6.035599,28.057802,14.63061,23.480632,16.550526,25.996077,8.409800,13.711223,9.912888
min,1.000000,1930.000000,1.000000,1.000000,31.000000,0.000000,0.000000,0.000000,0.000000,65.000000,23.00000,4.000000,9.000000,0.000000,0.000000,3.000000,2.000000
25%,1.000000,2020.000000,3.000000,6.000000,875.000000,0.000000,13.000000,7.000000,0.000000,100.000000,57.00000,32.000000,53.000000,6.000000,0.000000,10.000000,4.000000
50%,1.000000,2022.000000,6.000000,13.000000,2224.000000,3.000000,34.000000,38.000000,0.000000,121.000000,69.00000,51.000000,66.000000,18.000000,0.000000,12.000000,6.000000
75%,2.000000,2022.000000,9.000000,22.000000,5542.000000,16.000000,88.000000,87.000000,2.000000,140.000000,78.00000,70.000000,77.000000,43.000000,0.000000,24.000000,11.000000
max,8.000000,2023.000000,12.000000,31.000000,52898.000000,147.000000,672.000000,275.000000,58.000000,206.000000,96.00000,97.000000,97.000000,97.000000,91.000000,97.000000,64.000000

In [79]:
df.isna().any()

track_name              False
artist(s)_name          False
artist_count            False
released_year           False
released_month          False
released_day            False
in_spotify_playlists    False
in_spotify_charts       False
streams                 False
in_apple_playlists      False
in_apple_charts         False
in_deezer_playlists     False
in_deezer_charts        False
in_shazam_charts         True
bpm                     False
key                      True
mode                    False
danceability_%          False
valence_%               False
energy_%                False
acousticness_%          False
instrumentalness_%      False
liveness_%              False
speechiness_%           False
dtype: bool

In [80]:
df.isna().sum().sum()

np.int64(145)

In [81]:
df = df.drop(columns=['in_shazam_charts', 'key'])

In [82]:
df.columns

Index(['track_name', 'artist(s)_name', 'artist_count', 'released_year',
       'released_month', 'released_day', 'in_spotify_playlists',
       'in_spotify_charts', 'streams', 'in_apple_playlists', 'in_apple_charts',
       'in_deezer_playlists', 'in_deezer_charts', 'bpm', 'mode',
       'danceability_%', 'valence_%', 'energy_%', 'acousticness_%',
       'instrumentalness_%', 'liveness_%', 'speechiness_%'],
      dtype='str')

In [83]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    str
 1   artist(s)_name        953 non-null    str
 2   artist_count          953 non-null    int64
 3   released_year         953 non-null    int64
 4   released_month        953 non-null    int64
 5   released_day          953 non-null    int64
 6   in_spotify_playlists  953 non-null    int64
 7   in_spotify_charts     953 non-null    int64
 8   streams               953 non-null    str
 9   in_apple_playlists    953 non-null    int64
 10  in_apple_charts       953 non-null    int64
 11  in_deezer_playlists   953 non-null    str
 12  in_deezer_charts      953 non-null    int64
 13  bpm                   953 non-null    int64
 14  mode                  953 non-null    str
 15  danceability_%        953 non-null    int64
 16  valence_%             953 non-null    int64
 17  energy_%              953 non-null    int64
 18  acousticness_%        953 non-null    int64
 19  instrumentalness_%    953 non-null    int64
 20  liveness_%            953 non-null    int64
 21  speechiness_%         953 non-null    int64
dtypes: int64(17), str(5)
memory usage: 163.9 KB

In [84]:
# drop row with wrong stream count value
df = df[df['streams'] != 'BPM110KeyAModeMajorDanceability53Valence75Energy69Acousticness7Instrumentalness0Liveness17Speechiness3']

In [85]:
# Convert 'streams' column from string to int value
df['streams'] = df['streams'].astype('int')

In [86]:
df.info()

<class 'pandas.DataFrame'>
Index: 952 entries, 0 to 952
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            952 non-null    str
 1   artist(s)_name        952 non-null    str
 2   artist_count          952 non-null    int64
 3   released_year         952 non-null    int64
 4   released_month        952 non-null    int64
 5   released_day          952 non-null    int64
 6   in_spotify_playlists  952 non-null    int64
 7   in_spotify_charts     952 non-null    int64
 8   streams               952 non-null    int64
 9   in_apple_playlists    952 non-null    int64
 10  in_apple_charts       952 non-null    int64
 11  in_deezer_playlists   952 non-null    str
 12  in_deezer_charts      952 non-null    int64
 13  bpm                   952 non-null    int64
 14  mode                  952 non-null    str
 15  danceability_%        952 non-null    int64
 16  valence_%             952 non-null    int64
 17  energy_%              952 non-null    int64
 18  acousticness_%        952 non-null    int64
 19  instrumentalness_%    952 non-null    int64
 20  liveness_%            952 non-null    int64
 21  speechiness_%         952 non-null    int64
dtypes: int64(18), str(4)
memory usage: 171.1 KB

In [87]:
# check released_year unique values
print(df['released_year'].unique())

[2023 2019 2022 2013 2014 2018 2017 2020 2016 2012 1999 2008 1975 2021
 2015 2011 2004 1985 2007 2002 2010 1983 1992 1968 1984 2000 1997 1995
 2003 1973 1930 1994 1958 1957 1963 1959 1970 1971 1952 1946 1979 1950
 1942 1986 2005 1991 1996 1998 1982 1987]

In [88]:
len(df['released_year'].unique())

50

In [89]:
with pd.option_context('display.max_rows', None):
    display(df['released_year'].value_counts())

released_year
2022    402
2023    175
2021    119
2020     37
2019     36
2017     23
2016     18
2013     13
2014     13
2015     11
2018     10
2012     10
2011     10
2010      7
2002      6
1999      5
2004      4
1984      4
2000      4
1958      3
1963      3
2008      2
1975      2
1985      2
1995      2
2003      2
1957      2
1959      2
1986      2
1991      2
1982      2
2007      1
1983      1
1992      1
1968      1
1997      1
1973      1
1930      1
1994      1
1970      1
1971      1
1952      1
1946      1
1979      1
1950      1
1942      1
2005      1
1996      1
1998      1
1987      1
Name: count, dtype: int64

-> Released year between 2011 to 2022 yields 10 or more rows of data.

In [90]:
print(df.columns)

Index(['track_name', 'artist(s)_name', 'artist_count', 'released_year',
       'released_month', 'released_day', 'in_spotify_playlists',
       'in_spotify_charts', 'streams', 'in_apple_playlists', 'in_apple_charts',
       'in_deezer_playlists', 'in_deezer_charts', 'bpm', 'mode',
       'danceability_%', 'valence_%', 'energy_%', 'acousticness_%',
       'instrumentalness_%', 'liveness_%', 'speechiness_%'],
      dtype='str')

In [91]:
def top_stream_counts(df, year):
    this_year_df = df[df['released_year']==year][['track_name', 'artist(s)_name', 'streams']]
    this_year_sorted = this_year_df.sort_values(by='streams', ascending=False)
    top10 = this_year_sorted.head(10)
    top10_sorted = top10.sort_values(by='streams', ascending=True)

    fig = px.bar(
        top10_sorted,
        y = 'track_name',
        x = 'streams',
        hover_data='artist(s)_name',
        title = 'Top 10 most streamed songs released in ' + str(year),
        text_auto = True,
        orientation = 'h'
    )
    fig.update_layout(
        height=700, # give each bar enough thickness
        bargap=0.2, 
        yaxis_title="",
        xaxis_title="Stream Count",
        template='plotly_white',
        margin=dict(l=10, r=20, t=50, b=40)
    )
    #fig.show()
    return fig

In [92]:
# let's test our bar chart
top_stream_counts(df, 2013).show()

In [93]:
# double check values
print(df[df.track_name=='Anti-Hero']['streams'])

33    999748277
Name: streams, dtype: int64

In [118]:
def stream_vs_playlist(df, year):
    this_year_df = df[df['released_year']==year][['track_name', 'artist(s)_name', 'streams', 'in_spotify_charts', 'in_spotify_playlists']]
    
    fig = px.scatter(
            this_year_df, 
            x='in_spotify_playlists', 
            y='streams',
            opacity=0.7,                 
            size='in_spotify_charts',                       
            hover_name='track_name',          
            hover_data=['artist(s)_name', 'in_spotify_charts'],
            title='Streams vs. Number of Spotify playlists of top songs released in ' + str(year)
        )
    
    fig.update_layout(template='plotly_white')
    #fig.show()
    return fig

In [122]:
stream_vs_playlist(df, 2022).show()

In [96]:
fig = px.scatter(
            df, 
            x='in_spotify_playlists', 
            y='streams',
            opacity=0.5,                 
            size='in_spotify_charts',                       
            hover_name='track_name',          
            hover_data=['artist(s)_name', 'in_spotify_charts'],
            title='Streams vs. Number of Spotify playlists of most streamed songs in 2023' 
        )
    
fig.update_layout(template='plotly_white')
fig.show()

In [97]:
fig = px.scatter(
            df, 
            x='in_spotify_playlists', 
            y='streams',
            opacity=0.5,                 
            size='in_spotify_charts',                       
            hover_name='track_name',          
            hover_data=['artist(s)_name', 'in_spotify_charts'],
            title='Streams vs. Number of Spotify playlists of most streamed songs in 2023' 
        )
    
fig.update_layout(template='plotly_white')
fig.show()

In [98]:
fig = px.scatter(
            df, 
            x='in_spotify_charts', 
            y='in_spotify_playlists',
            opacity=0.5,                                        
            hover_name='track_name',          
            hover_data=['artist(s)_name'],
            title='Number of Spotfify playlists vs. charts of most streamed songs in 2023' 
        )
    
fig.update_layout(template='plotly_white')
fig.show()

In [99]:
fig = px.scatter(
            df, 
            x='in_spotify_playlists', 
            y='streams',
            opacity=0.5,                 
            size='in_spotify_charts',                       
            hover_name='track_name',          
            hover_data=['artist(s)_name', 'in_spotify_charts'],
            title='Streams vs. Number of Spotify playlists of most streamed songs in 2023' 
        )
    
fig.update_layout(template='plotly_white')
fig.show()

In [100]:
def released_month_hist(df, year):
    this_year_df = df[df['released_year']==year]['released_month']

    fig = px.histogram(
        this_year_df,
        x = 'released_month',
        nbins = 12,
        title = 'Number of most streamed songs released each month in ' + str(year),
        text_auto = True
    )
    fig.update_xaxes(
        dtick=1,                            
        tickvals=list(range(1, 13)),       
        ticktext=['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']        
    )                           
    fig.update_layout(
        xaxis_title='Released month in ' + str(year),
        yaxis_title='Number of most streamed songs in 2023',
        bargap=0.2,
        template='plotly_white'
    )
    
    #fig.show()
    return fig

In [101]:
released_month_hist(df, 2022).show()

In [102]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

def dve_vplot(df, year):
    cols = ['danceability_%', 'valence_%', 'energy_%']
    this_year_df = df[df['released_year']==year][cols]

    fig = make_subplots(
        rows=1, 
        cols=3, 
        subplot_titles=['Danceability', 'Valence', 'Energy'],
        shared_yaxes=True
    )
    for i, col in enumerate(cols, start=1):
        fig.add_trace(
            go.Violin(
                y=this_year_df[col],
                name=col.replace('_%', ' percentage').capitalize(),
                box_visible=True,            
                spanmode='hard', # to prevent plots go beyond 100%                   
                showlegend=False
            ),
            row=1, col=i
        )
    fig.update_yaxes(range=[0, 105], title_text="Percentage (%)", row=1, col=1)
    fig.update_layout(
        title='Audio feature distributions of top songs released in ' + str(year),
        template='plotly_white',
        height=500,
        margin=dict(t=80, b=40, l=60, r=40)
    )
    
    #fig.show()
    return fig

In [103]:
dve_vplot(df, 2023).show()

In [114]:
def create_dashboard(df, year):
    ax1 = top_stream_counts(df, year)
    ax2 = released_month_hist(df, year)
    ax3 = stream_vs_playlist(df, year)
    ax4 = dve_vplot(df, year)

    titles = [
        ax1.layout.title.text if ax1.layout.title.text else "Top Stream Counts",
        ax2.layout.title.text if ax2.layout.title.text else "Streams vs Playlist",
        ax3.layout.title.text if ax3.layout.title.text else "Release Month Distribution",
        ax4.layout.title.text if ax4.layout.title.text else "Audio Features"
    ]

    dashboard = make_subplots(
        rows=2, 
        cols=2,
        subplot_titles=titles,
        horizontal_spacing=0.12,
        vertical_spacing=0.15
    )

    fig_map = [
        (ax1, 1, 1),
        (ax2, 1, 2),
        (ax3, 2, 1),
        (ax4, 2, 2)
    ]

    for fig, r, c in fig_map:
        for trace in fig.data:
            dashboard.add_trace(trace, row=r, col=c)

    # this is to fix x-label on histogram
    month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 
                   'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
                   
    dashboard.update_xaxes(
        dtick=1,
        tickvals=list(range(1, 13)),
        ticktext=month_names,
        range=[0.5, 12.5],
        row=1, col=2 # apply this update x-axis on row 1, col 2, aka, ax2 - histogram only
    )

    dashboard.update_layout(
        title_text=f"Spotify Music Dashboard ({year})",
        title_font_size=20,
        height=900,
        template='plotly_white',
        showlegend=False,
        bargap=0.15,  # <--- Restores spacing between bars globally across subplots
        margin=dict(t=100, b=50, l=50, r=50)
    )

    dashboard.show()

In [115]:
create_dashboard(df, 2022)

In [123]:
import ipywidgets as widgets
from ipywidgets import interact

year_options = list(range(2011, 2024))

@interact(
    year=widgets.Dropdown(
        options=year_options,
        value=2023, # default option
        description='Released year: ',
        style={'description_width': 'initial'}
    )
)
def interactive_dashboard(year):
    # Calls your existing function with the selected year
    create_dashboard(df, year)

interactive(children=(Dropdown(description='Released year: ', index=12, options=(2011, 2012, 2013, 2014, 2015,…